Docs & Tutorial Sync
smartmind-team/thanosql-tutorial pull request #15
Opened 2022-08-30 08:02 UTC by yeemh

- 파일명 영문화
- wget 내용 추가 (hello_thanoSQL, tutorial_wget_list)
- .pages 추가

2022-08-30 08:02 UTC, lazyduo commented
Task linked: [CU-2z56cu2 ipynb mkdocs sync 맞추기](https://app.clickup.com/t/2z56cu2)

2022-08-30 23:35 UTC, inwookie requested changes

2022-08-30 23:35 UTC, inwookie commented on tutorial/tutorial_wget_list.md
> +| `키워드로 이미지 검색하기`       | https://raw.githubusercontent.com/smartmind-team/thanosql-tutorial/main/tutorial/thanosql_search/select_image_query.ipynb |
이거 url들 아직 wget 사용 못하는거 같은데 thanosql-tutorial에 반영이 안된거죠?

2022-08-30 23:35 UTC, inwookie commented on tutorial/thanosql_ml/classification/.pages
> +    - classification_Electra.ipynb
Electra 랑 convNext naming 통일 필요할거 같아요

2022-08-31 00:55 UTC, yeemh commented on tutorial/thanosql_ml/classification/.pages
> +    - classification_Electra.ipynb
그냥 다 소문자로 수정하죠

2022-08-31 00:56 UTC, yeemh commented on tutorial/tutorial_wget_list.md
> +| `키워드로 이미지 검색하기`       | https://raw.githubusercontent.com/smartmind-team/thanosql-tutorial/main/tutorial/thanosql_search/select_image_query.ipynb |
아직 main에 안올라가서 안됩니다. url 중간에 main을 feat/#2z56cu2 로 바꿔서 테스트 하면 될겁니다.

2022-08-31 01:02 UTC, lazyduo commented on tutorial/thanosql_ml/classification/.pages
> +    - classification_Electra.ipynb
파일 이름은 웬만하면 소문자 snake_case 해주세요

2022-08-31 01:03 UTC, yeemh commented on tutorial/tutorial_wget_list.md
> +| `키워드로 이미지 검색하기`       | https://raw.githubusercontent.com/smartmind-team/thanosql-tutorial/main/tutorial/thanosql_search/select_image_query.ipynb |
! wget https://raw.githubusercontent.com/smartmind-team/thanosql-tutorial/feat/%232z56cu2/tutorial/thanosql_search/simclr_image_search.ipynb

2022-08-31 01:15 UTC, inwookie commented on tutorial/tutorial_wget_list.md
> +| `키워드로 이미지 검색하기`       | https://raw.githubusercontent.com/smartmind-team/thanosql-tutorial/main/tutorial/thanosql_search/select_image_query.ipynb |
확인했습니다!!

2022-08-31 02:09 UTC, yeemh commented on tutorial/thanosql_ml/classification/.pages
> +    - classification_Electra.ipynb
수정했습니다. thanosql-docs는 현재 올라가 있는 pr 모두 완료한 후에 hotfix로 반영하겠습니다.

2022-08-31 05:05 UTC, inwookie approved these changes
👍

2022-08-31 05:06 UTC, jyoon0808 commented on tutorial/.pages
> +    - hello_thanoSQL.ipynb
이 파일도 소문자로 수정필요할 것 같습니다.

2022-08-31 05:09 UTC, jyoon0808 commented on tutorial/hello_thanoSQL.ipynb
> +    "! wget [가져올 tutorial의 Github URL]\n",
! 뒤에 스페이스.. 불편.. :(

2022-08-31 05:11 UTC, jyoon0808 commented on tutorial/tutorial_wget_list.md
> +! wget [가져올 tutorial의 Github URL]
스페이스.. :(

2022-08-31 05:39 UTC, merged

2022-08-31 05:39 UTC, yeemh commented on tutorial/.pages
> +    - hello_thanoSQL.ipynb
수정 했습니다.