[WIP] 튜토리얼 수정
smartmind-team/thanosql-tutorial pull request #41
Opened 2022-11-08 06:18 UTC by yeemh

- pre-built-model 이름 변경
- option 추가
    - emb_col
    - column_name
- output에 building model..., searching... 삭제

2022-11-08 06:18 UTC, lazyduo commented
Task linked: [CU-35ymgef Docs& Tutorial 수정](https://app.clickup.com/t/35ymgef)

2022-11-10 06:41 UTC, Bing-su approved these changes

2022-11-17 07:59 UTC, yeemh commented
해당 내용은 먼저 docs에 반영하고 배포해야해서 리뷰해주세요
@inwookie @jyoon0808 @Indoo-Park @sk37025

2022-11-17 23:46 UTC, sk37025 approved these changes

2022-11-18 01:11 UTC, stevensjcho approved these changes
English LGTM 👍

2022-11-18 01:13 UTC, inwookie requested changes
En 쪽 다 확인 했습니다. minor issue 빼고는 다 괜찮은거 같습니다. `wget_list.md`는 이제 사용 하지 않는건가요?

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_ml/classification/automl_classification.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "- [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_ml/classification/image_classification.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "- [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_ml/classification/text_classification.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "- [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_ml/regression/automl_regression.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "- [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_ml/udm_tutorial.ipynb
> +    "#### Create a Dataframe to Insert into the ThanoSQL "
```suggestion
    "#### Create a Dataframe to Insert into the ThanoSQL Workspace Database"
```
이게 더 나을까요? 아니면 그냥 ThanoSQL에서 끊는게 맞을까요?

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_search/search_image_by_image.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "- [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:13 UTC, inwookie commented on tutorial_en/thanosql_search/search_text_by_text.ipynb
> +    "* [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "* [How to Upload to ThanoSQL Workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:14 UTC, stevensjcho commented on tutorial_en/thanosql_search/search_text_by_text.ipynb
> +    "* [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```suggestion
    "* [How to Upload to the ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:16 UTC, yeemh commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
![image](https://user-images.githubusercontent.com/51910605/202594041-a1ec1c4d-bd98-4fb8-a5c3-80758ffc6cb8.png)
해당 링크 페이지 제목 자체가 workspace로 되어있어서 소문자로 가는게 맞을거 같습니다.

2022-11-18 01:18 UTC, yeemh commented on tutorial_en/hello_thanosql.ipynb
> +       "7     simclr      SimCLR  2022-11-03 00:00:00"
S3에 올라가있나요?

2022-11-18 01:19 UTC, yeemh commented on tutorial_en/thanosql_ml/udm_tutorial.ipynb
> +    "#### Create a Dataframe to Insert into the ThanoSQL "
제목에서는 ThanoSQL만 써줘도 될거가탕요

2022-11-18 01:21 UTC, inwookie commented on tutorial_en/hello_thanosql.ipynb
> +       "7     simclr      SimCLR  2022-11-03 00:00:00"
넵! local & prod 둘다 반영되어 있습니다

2022-11-18 01:21 UTC, inwookie commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
그러면 Upload가 upload가 되어야 할거 같아요

2022-11-18 01:22 UTC, stevensjcho commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
the 더해 주세요
```suggestion
    "- [How to Upload to the ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
```

2022-11-18 01:22 UTC, inwookie commented on tutorial_en/thanosql_ml/udm_tutorial.ipynb
> +    "#### Create a Dataframe to Insert into the ThanoSQL "
네네 very nice 🔥

2022-11-18 01:24 UTC, inwookie commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
저거 제목도 How to upload your data to the ThanoSQL workspace! 🎁

2022-11-18 02:03 UTC, yeemh commented on tutorial_en/hello_thanosql.ipynb
> +       "7     simclr      SimCLR  2022-11-03 00:00:00"
반영했습니다 [feat: add hello_thanosql pre-built sbert](https://github.com/smartmind-team/thanosql-tutorial/pull/41/commits/6f4a794f0a314037ebae9db8d9ad1d03d0b43004)

2022-11-18 02:10 UTC, yeemh commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
nooooooo

2022-11-18 02:14 UTC, yeemh commented
> En 쪽 다 확인 했습니다. minor issue 빼고는 다 괜찮은거 같습니다. `wget_list.md`는 이제 사용 하지 않는건가요?

`wget_list.md`는 docs에서 관리합니다!

2022-11-18 02:17 UTC, yeemh commented on tutorial_en/thanosql_ml/audio_recognition/speech_recognition.ipynb
> +    "- [How to Upload to ThanoSQL workspace](https://docs.thanosql.ai/en/getting_started/data_upload/)\n",
done
[fix: Upload -> upload, add the](https://github.com/smartmind-team/thanosql-tutorial/pull/41/commits/7623b5546966d3789d53edf17832232e8491002f)

2022-11-18 02:22 UTC, stevensjcho approved these changes
👍 LGTM

2022-11-18 02:25 UTC, Indoo-Park reviewed
한글 리뷰 끝! 고생하셨습니다

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_text_by_text.ipynb
> +    "                <li>\"column_name\" : 데이터 테이블에서 검색 결과를 담을 컬럼 이름을 정의합니다.(default: \"search_result\")</li>\n",
~ 데이터 테이블에서 검색 결과를 담을 컬럼의 이름 (default : ~ )

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_text_by_text.ipynb
> +    "                <li>\"emb_col\" : 데이터 테이블에서 수치화된 결과를 담은 컬럼</li>\n",
~ 컬럼의 이름 (default: convert_result ?)

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_text_by_text.ipynb
> +    "        <li>\"<strong>SEARCH KEYWORD</strong>\" 쿼리 구문은 키워드를 검색하기 위한 알고리즘으로 사용합니다.</li>\n",
![image](https://user-images.githubusercontent.com/55899856/202600255-5947d018-fb7c-430f-af51-4dfa1092362e.png)

tone & manner ...

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_text_by_text.ipynb
>      "    <h4 class=\"admonition-title\">쿼리 세부 정보</h4>\n",
위 search 문에 있는 쿼리 세부 정보와 동일한데 또 쓸 필요는 없어 보입니다. 
똑같은 옵션 설명보다는 각 쿼리가 무슨 쿼리인지 설명을 해주는 것이 좋아 보여요.

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "            <li>\"table_name\" : ThanoSQL 워크스페이스 DB 내에 저장될 테이블 이름을 정의합니다. </li>\n",
ThanoSQL 워크스페이스 DB 내에 저장될 테이블의 이름

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "            <li>\"column_name\" : 데이터 테이블에서 수치화된 결과를 담을 컬럼 이름을 정의합니다.(default: \"convert_result\")</li>\n",
데이터 테이블에서 수치화된 결과를 담을 컬럼의 이름 (default: ~)

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "            <li>\"video_col\" : 데이터 테이블에서 비디오의 경로를 담은 컬럼(default: \"video_path\")</li>\n",
데이터 테이블에서 비디오의 경로를 담은 컬럼이 이름 ~

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "            <li>\"column_name\" : 데이터 테이블에서 검색 결과를 담을 컬럼 이름을 정의합니다.(default: \"search_result\")</li>\n",
데이터 테이블에서 검색 결과를 담을 컬럼의 이름 (default: ~)

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "            <li>\"emb_col\" : 데이터 테이블에서 수치화된 결과를 담은 컬럼</li>\n",
데이터 테이블에서 수치화된 결과를 담은 컬럼의 이름

2022-11-18 02:25 UTC, Indoo-Park commented on tutorial/thanosql_search/search_video_by_text.ipynb
> +    "    SELECT video_path, label, score\n",
PRINT VIDEO 쿼리 구문을 통해
최종 두 개의 동영상 파일이 저장 되었다는 결과? 에 대한 설명이 짧게 나마 추가 되면 좋겠습니다.

2022-11-18 02:29 UTC, Bing-su commented on tutorial/hello_thanosql.ipynb
> +       "1        vqa         VQA  2022-11-03 00:00:00\n",
VQA -> VILT 😢

2022-11-18 05:23 UTC, yeemh commented on tutorial/hello_thanosql.ipynb
> +       "1        vqa         VQA  2022-11-03 00:00:00\n",
수정했습니다. [fix: change vqa to vilt](https://github.com/smartmind-team/thanosql-tutorial/pull/41/commits/73bdb1c1fdb01ab0b475ace4cfc787ea5166dbfc)

2022-11-18 05:40 UTC, yeemh commented
@Indoo-Park tone&manner 맞추는건 다음주에 진행할게요.

2022-11-18 05:41 UTC, merged