Timeseries forecasting
smartmind-team/thanosql-tutorial pull request #68
Opened 2023-01-02 07:30 UTC by Indoo-Park

# Description (개요) 

- [x] timseries_forecasting_tutorial_ko
- [ ] timseries_forecasting_tutorial_en
- [ ] timseries_forecasting_tech-doc_ko
- [ ] timseries_forecasting_tech-doc_en 

## Keep in Mind

If you are creating a new tutorial, your first commit should always be a copy of the tutorial template. This will allow reviewers to see what has been changed from the template, making the review process much more efficient.

## Type of change (작업사항)

Please delete options that are not relevant and check out the type of change.

- [x] Tutorial creation 
- [ ] Tutorial fix 

Following templates can be found from the [Tech-wiki Tutorial](https://github.com/smartmind-team/tech-wiki/tree/main/project/thanosql/tutorial). 

## Writing Convention

Make sure to check out the [Writing Convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md). 

## Review Process

Review should be conducted by at least two people.

2023-01-02 08:33 UTC, yeemh requested changes
맨 처음 add template commit(https://github.com/smartmind-team/thanosql-tutorial/pull/68/commits/123935258297ac96f2e04ebf694af89ffec8bce1) 은 없어도 될 것 같습니다. 템플릿 추가된건 삭제 부탁드립니다!

2023-01-02 08:33 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"overwrite\": 동일 이름의 데이터 세트가 존재하는 경우 덮어쓰기 가능 유무 설정. True일 경우 기존 데이터 세트는 새로운 데이터 세트로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```suggestion
    "            <li>\"overwrite\": 동일 이름의 데이터 세트가 존재하는 경우 덮어쓰기 가능 여부 설정. True일 경우 기존 데이터 세트는 새로운 데이터 세트로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```

2023-01-02 08:33 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"overwrite\": 동일 이름의 테이블이 데이터베이스 상에 존재하는 경우 덮어쓰기 가능 유무 설정. True일 경우 기존 테이블은 새로운 테이블로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```suggestion
    "            <li>\"overwrite\": 동일 이름의 테이블이 데이터베이스 상에 존재하는 경우 덮어쓰기 가능 여부 설정. True일 경우 기존 테이블은 새로운 테이블로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```

2023-01-02 08:33 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"overwrite\": 동일 이름의 모델이 존재하는 경우 덮어쓰기 가능 유무 설정. True일 경우 기존 모델은 새로운 모델로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```suggestion
    "            <li>\"overwrite\": 동일 이름의 모델이 존재하는 경우 덮어쓰기 가능 여부 설정. True일 경우 기존 모델은 새로운 모델로 변경됨 (bool, optional, True|False, default: False)</li>\n",
```

2023-01-03 05:24 UTC, Indoo-Park commented
> 맨 처음 add template commit([1239352](https://github.com/smartmind-team/thanosql-tutorial/commit/123935258297ac96f2e04ebf694af89ffec8bce1)) 은 없어도 될 것 같습니다. 템플릿 추가된건 삭제 부탁드립니다!

삭제했습니다

2023-01-03 05:32 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    ")\n",
> Code Convention에 따르면 OPTIONS의 닫는 괄호 위치는 탭 하나 추가해야할 것 같습니다. (@Indoo-Park )
> 
> ![image](https://user-images.githubusercontent.com/83015818/210301459-64ef8742-e166-4444-ace5-e9b9383265b5.png)

```py
OPTIONS (
    ...
    )
```
수정 완료

2023-01-03 06:24 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이전 단계에서 (생성한) 시계열 예측 모델을 사용해 테스트 세트의 1주일 전력사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
다른 튜토리얼들도 이미 붙어져 있어서 붙이는게 나아 보이네요.
근데 지금 읽어보니 문장 자체가 좀 이상하네요 데이터 세트 != 데이터 테이블인데 이 문장도 릴리즈 후 수정할 지 논의하죠.

2023-01-03 06:25 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이전 단계에서 (생성한) 시계열 예측 모델을 사용해 테스트 세트의 1주일 전력사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
@inwookie

2023-01-03 07:01 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "    <p> 시계열 데이터(time series data)란 시간을 기준으로 측정된 자료를 말합니다. 시계열 자료는 연도별, 분기별, 월별, 일별 또는 시간별등 시간의 경과(흐름)에 따라 순서대로 관측되는 자료입니다. 그 예로 국내총생산(GDP), 물가 지수, 판매량, 종합주가지수(KOSPI), 강우량, 태양 흑점수, 실험 및 관측자료 등이 있
띄어 쓰는 걸 수정했어요

2023-01-03 07:02 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "시계열 분석은 일정한 시간 간격으로 표시된 자료의 특성(추세변동, 계절변동, 순환변동, 불규칙변동)을 파악하여 미래를 예측하는 분석방법입니다. 시계열 분석을 통해서 내년도 판매량, 다음달 항공기 이용 승객, 앞으로 4개월 동안의 변화, 다음 분기에 예상되는 변화 등을 예측할 수 있습니다. 시계열 분석의 단점은 연구자가 만든 시계열모형을 이용하여
수정했습니다

2023-01-03 07:04 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "- 온라인 쇼핑몰 내에서 다음달의 판매량을 미리 예측할 수 있습니다. 고객 데이터를 바탕으로 계절별, 분기별, 시간별 고객들의 구매 특징을 시계열모델이 학습 할 수 있도록 하여 예측 값을 바탕으로 맞춤화된 전략 수립을 가능하게 합니다.\n",
> 시계열모델 -> 시계열 모델로 띄어 쓰기 부탁드립니다. 그리고 전력 사용량을 쓸지 전력 사용량을 쓸지도 확인해야할 것 같습니다.

전력 사용량으로 통일 했습니다

2023-01-03 07:07 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "    <p>👉 DACON 전력사용량 예측 AI 경진대회의 빌딩 별 전력사용량 데이터세트를 사용합니다. 데이터 세트는 60개 건물들의 전력사용량 및 기온, 습도, 풍속 등의 기상 데이터가 포함되어 있습니다. ThanoSQL에서 제공하는 데이터세트는 시계열 모델을 학습하기 위해 미리 전처리과정을 거친 데이터로써 학습용 데이터 세트는 2020년 6월
> 전처리과정 -> 전처리과정 그리고
> 
> ```
> 데이터 세트는 2020년 6월 1일부터 2020년 8월 24일, 테스트용 데이터 세트는 2020년 8월 25일 부터 2020년 8월 31일까지로 구성되어 있습니다.
> ```
> 
> 에서 `8월 25일부터`로 붙이는게 나을것 같습니다.

전처리 과정, ~일부터 로 수정했습니다

2023-01-03 07:13 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "        <li>time_idx: 시간순서를 나타내는 인덱스. 시계열 모델 학습에 필요</li>\n",
수정 했습니다

2023-01-03 07:17 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "        <li>\"<strong>BUILD MODEL</strong>\" 쿼리 구문을 사용하여 <strong>{모델 이름}</strong>이라는 모델을 만들고 학습시킵니다.</li>\n",
> ㅋㅋㅋㅋ 여긴 아직 수정이 안되어 있네요! 수정 부탁드립니다!

엇. 수정했습니다 ㅎㅎ

2023-01-03 07:23 UTC, Indoo-Park commented
리뷰 반영했습니다 @sk37025 @yeemh

2023-01-03 08:40 UTC, yeemh reviewed
한글 튜토리얼 리뷰입니다.
영문 튜토리얼에도 중복될 거 같은 내용들은 같이 고쳐주세요 🤞

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"group_id_cols\": 시계열 식별자 컬럼. 데이터 세트에 여러 시계열이 존재하는 경우 해당 식별자를 리스트 형태로 기재합니다 (List[str], default: [])</li>\n",
```suggestion
    "            <li>\"group_id_cols\": 시계열 식별자 컬럼. 데이터 세트에 여러 시계열이 존재하는 경우 해당 식별자를 리스트 형태로 기재함 (List[str])</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"group_id_cols\": 시계열 식별자 컬럼. 데이터 세트에 여러 시계열이 존재하는 경우 해당 식별자를 리스트 형태로 기재합니다 (List[str], default: [])</li>\n",
튜토리얼에서 option 밑의 매개변수 설명은 명사로 끝납니다.
![image](https://user-images.githubusercontent.com/51910605/210320713-77eebabd-b7c1-444d-847b-da24c92d57ce.png)
[convention](https://github.com/smartmind-team/tech-wiki/blob/main/project/thanosql/docs/writing_convention.md#tutorial) 참고

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"min_encoder_length\": 모델이 예측할 때 사용할 과거 데이터의 최소 길이(time_idx). 기본값은 max_encoder_length 값에 맞춰집니다 (int, default: 'max_encoder_length')</li>\n",
default는 그냥 빼는게 오히려 덜 헷갈릴 거 같네요. 그리고 이 매개변수는 optional로 보는게 맞지 않을까요? 사용자가 안넣어도 자동으로 설정이 되는거니까.
```suggestion
    "            <li>\"min_encoder_length\": 모델이 예측할 때 사용할 과거 데이터의 최소 길이(time_idx). 기본값은 max_encoder_length 값에 맞춰짐 (int, optional)</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"min_prediction_length\": 최소 예측 길이. 기본값은 max_encoder_length 값에 맞춰집니다 (str, default: 'max_prediction_length')</li>\n",
```suggestion
    "            <li>\"min_prediction_length\": 최소 예측 길이. 기본값은 max_encoder_length 값에 맞춰짐 (str, default: 'max_prediction_length')</li>\n",
```
위에 참고하여 얘도 optional..?

인두님 판단하에 이 변수들에 대해서 통일감 있게만 맞춰주세요 (optional, default 관련하여)
- min_encoder_length
- max_encoder_length
- min_prediction_length
- max_prediction_length

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"max_prediction_length\": 최대 예측 길이. 너무 짧지 않도록 선택합니다 (int, default: 24)</li>\n",
```suggestion
    "            <li>\"max_prediction_length\": 최대 예측 길이. 너무 짧지 않도록 선택 (int, default: 24)</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"group_normalizer\": GroupNormalizer의 사용 여부 (bool, optional, default: False)</li>\n",
```suggestion
    "            <li>\"group_normalizer\": GroupNormalizer의 사용 여부 (bool, optional, True|False, default: False)</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_known_categorical_cols\": 시간이 지남에 따라 변경되고 미래 값이 미리 알려진 범주형 변수 리스트 e.g. 공휴일 (List[str], default: [])</li>\n",
```suggestion
    "            <li>\"time_varying_known_categorical_cols\": 시간이 지남에 따라 변경되고 미래 값이 미리 알려진 범주형 변수 리스트 e.g. 공휴일 (List[str])</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_known_real_cols\": 시간이 지남에 따라 변화하고 미래에 알려진 연속 변수 리스트 (List[str], default: [])</li>\n",
```suggestion
    "            <li>\"time_varying_known_real_cols\": 시간이 지남에 따라 변화하고 미래에 알려진 연속 변수 리스트 (List[str])</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_unknown_real_cols\": 시간이 지남에 따라 변경되고 미래에 알려지지 않은 연속형 변수 리스트. 여기에 타겟 값을 포함하는 것이 좋습니다 (List[str], default: [])</li>\n",
```suggestion
    "            <li>\"time_varying_unknown_real_cols\": 시간이 지남에 따라 변경되고 미래에 알려지지 않은 연속형 변수 리스트. 여기에 타겟 값을 포함하는 것이 좋음 (List[str])</li>\n",
```
"좋음"은 좀 이상하긴 하네요...

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"validate\": 교차검증 사용옵션 (bool, optional, default: False)</li>\n",
```suggestion
    "            <li>\"validate\": 교차검증 사용옵션 (bool, optional, True|False, default: False)</li>\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이전 단계에서 생성한 시계열 예측 모델을 사용해 테스트 세트의 1주일 전력 사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
```suggestion
    "이전 단계에서 생성한 시계열 예측 모델을 사용해 테스트 데이터 세트의 1주일 전력 사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이전 단계에서 생성한 시계열 예측 모델을 사용해 테스트 세트의 1주일 전력 사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
이건 굳이..? 싶긴하네요

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "## __4. 생성된 모델 평가__\n",
모델 평가가 예측보다 먼저 와야 합니다. 순서 바꿔주세요. (automl 참조)

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "%%thanosql \n",
```suggestion
    "%%thanosql\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "PREDICT USING elec_predict_model \n",
```suggestion
    "PREDICT USING elec_predict_model\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "        )\n",
```suggestion
    "    )\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "        result_col=\"tft_result\"\n",
```suggestion
    "        result_col='tft_result'\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "OPTIONS (      \n",
```suggestion
    "OPTIONS (\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "AS \n",
```suggestion
    "AS\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "* \n",
```suggestion
    "SELECT *\n",
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "\n"
```suggestion
    "## __4. 생성된 모델 평가__\n",
    "\n",
    "아래의 쿼리문을 실행하여 이전 단계에서 만든 예측 모델의 성능을 평가합니다."
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "FROM building_elec_test"
```suggestion
    "%%thanosql\n",
    "EVALUATE USING elec_predict_model\n",
    "AS\n",
    "SELECT *\n",
    "FROM building_elec_test"
```

2023-01-03 08:40 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "* [나만의 데이터 업로드하기](https://docs.thanosql.ai/ko/getting_started/data_upload/)\n",
```suggestion
    "이번 튜토리얼에서는 건물별 전력 사용량 데이터 세트를 사용하여 시계열 예측 모델을 만들어 보았습니다. 이번 튜토리얼은 성능보다는 빠른 작동위주로 진행하였습니다. 좀 더 나은 성능을 위해서는 데이터 세트에 최적화하여 학습 횟수를 늘리는 등의 정밀한 파라미터 튜닝이 필요합니다. 추가적인 데이터 전처리 과정 또한 모델의 성능을 향상 시킬 수 있습니다.\n",
    "\n",
    "* [나만의 데이터 업로드하기](https://docs.thanosql.ai/ko/getting_started/data_upload/)\n",
```

2023-01-03 09:00 UTC, yeemh commented
@Indoo-Park 
algorithm_list.md와 .pages에도 추가해주세요!

2023-01-03 10:56 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "시계열 분석은 일정한 시간 간격으로 표시된 자료의 특성(추세변동, 계절변동, 순환변동, 불규칙변동)을 파악하여 미래를 예측하는 분석방법입니다. 시계열 분석을 통해서 내년도 판매량, 다음달 항공기 이용 승객, 앞으로 4개월 동안의 변화, 다음 분기에 예상되는 변화 등을 예측할 수 있습니다. 시계열 분석의 단점은 연구자가 만든 시계열 모형을 이용하여
한/영 모두 수정 완료

2023-01-03 10:56 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "</div>\n",
한/영 모두 수정 완료

2023-01-03 10:57 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "시계열 분석은 일정한 시간 간격으로 표시된 자료의 특성(추세변동, 계절변동, 순환변동, 불규칙변동)을 파악하여 미래를 예측하는 분석방법입니다. 시계열 분석을 통해서 내년도 판매량, 다음달 항공기 이용 승객, 앞으로 4개월 동안의 변화, 다음 분기에 예상되는 변화 등을 예측할 수 있습니다. 시계열 분석의 단점은 연구자가 만든 시계열 모형을 이용하여
수정 완료

2023-01-03 10:58 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "- 온라인 쇼핑몰 내에서 다음달의 판매량을 미리 예측할 수 있습니다. 고객 데이터를 바탕으로 계절별, 분기별, 시간별 고객들의 구매 특징을 시계열 모델이 학습 할 수 있도록 하여 예측 값을 바탕으로 맞춤화된 전략 수립을 가능하게 합니다.\n",
수정완료

2023-01-03 10:59 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "- 전력 사용량을 미리 예측할 수 있습니다. 전력 사용량의 계절별 특성을 모델이 학습하여 다음 달 전력 사용량을 미리 예측하고 예측 값을 바탕으로 전력생산량을 조절하여 블랙아웃 현상을 사전에 방지 할 수 있습니다.\n",
수정 완료

2023-01-03 11:00 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "    <p>👉 DACON 전력 사용량 예측 AI 경진대회의 빌딩 별 전력 사용량 데이터 세트를 사용합니다. 데이터 세트는 60개 건물들의 전력 사용량 및 기온, 습도, 풍속 등의 기상 데이터가 포함되어 있습니다. ThanoSQL에서 제공하는 데이터 세트는 시계열 모델을 학습하기 위해 미리 전처리 과정을 거친 데이터로써 학습용 데이터 세트는 20
수정 완료

2023-01-03 11:02 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이번 튜토리얼에서는 시계열 예측 모델을 사용하여, 테스트용 데이터 세트의 일주일 전력 사용량을 예측하는 시계열 모델을 만들어 봅니다. "
수정 완료

2023-01-03 11:21 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"min_encoder_length\": 모델이 예측할 때 사용할 과거 데이터의 최소 길이(time_idx). 기본값은 max_encoder_length 값에 맞춰집니다 (int, default: 'max_encoder_length')</li>\n",
반영하여 수정했습니다

2023-01-03 11:21 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"min_prediction_length\": 최소 예측 길이. 기본값은 max_encoder_length 값에 맞춰집니다 (str, default: 'max_prediction_length')</li>\n",
반영하여 수정 완료

2023-01-03 11:25 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_unknown_real_cols\": 시간이 지남에 따라 변경되고 미래에 알려지지 않은 연속형 변수 리스트. 여기에 타겟 값을 포함하는 것이 좋습니다 (List[str], default: [])</li>\n",
하는게 좋음으로 수정 했습니다

2023-01-03 11:57 UTC, Indoo-Park commented
> algorithm_list.md

추가 했습니다.

2023-01-04 02:35 UTC, inwookie requested changes

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "To create a Electrictiy Consumption Forecasting model with the name <strong>elec_predict_model</strong> using the <strong>uilding_elec_train</strong> table, run the following query.\\\n",
```suggestion
    "To create an electricity consumption forecasting model with the name <strong>elec_predict_model</strong> using the <strong>uilding_elec_train</strong> table, run the following query.\\\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"target_col\": column denoting the target or list of columns denoting the target - categorical or continous (str, default: 'target')</li>\n",
```suggestion
    "            <li>\"target_col\":a column or list of columns representing the target -- categorical or continuous (str, default: 'target')</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_idx_col\": integer column denoting the time index. This columns is used to determine the sequence of samples. If there no missings observations, the time index should incr
```suggestion
    "            <li>\"time_idx_col\": an integer column denoting the time index. This column is used to determine the sequence of samples. If there are no missing observations, the time index should increase by 1 for each subsequent sample. The first time_idx for each series does not necessarily have to be 0, but any value is allowed (int, default: 'time_idx')</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"group_id_cols\": list of column names identifying a time series. This means that the group_ids identify a sample together with the time_idx. If you have only one timeseries, se
```suggestion
    "            <li>\"group_id_cols\": list of column names identifying a time series. This means that the group_ids identify a sample together with the time_idx. If you only have one timeseries, set this to the name of the constant column (List[str])</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"min_encoder_length\": minimum allowed length to encode. Defaults to max_encoder_length (int, optional)</li>\n",
```suggestion
    "            <li>\"min_encoder_length\": minimum allowed length to encode. The default value is max_encoder_length (int, optional)</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"max_prediction_length\": maximum prediction/decoder length (choose this not too short as it can help convergence) (int, default: 6)</li>\n",
```suggestion
    "            <li>\"max_prediction_length\": the maximum prediction/decoder length. This should not be too short because it can aid in convergence (int, default: 6)</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"group_normalizer\": if True, transformer that take group_ids, target and time_idx to normalize targets (bool, optional, True|False, default: False)</li>\n",
```suggestion
    "            <li>\"group_normalizer\": if True, a transformer that takes group_ids, target, and time_idx to normalize targets (bool, optional, True|False, default: False)</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_known_categorical_cols\": list of categorical variables that change over time and are known in the future, entries can be also lists which are then encoded togethe
```suggestion
    "            <li>\"time_varying_known_categorical_cols\": list of categorical variables that change over time and are known in the future; entries can also be lists, which are then encoded together (e.g. useful for special days or promotion categories)  (List[str]))</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "            <li>\"time_varying_unknown_real_cols\": list of continuous variables that change over time and are not known in the future. You might want to include your target here (List[str])</li
```suggestion
    "            <li>\"time_varying_unknown_real_cols\": list of continuous variables that change over time and are not known in the future. You should probably include your target here (List[str])</li>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "To use the elec_predict_model model created in the previous step for prediction of <strong>building_elec_test</strong>, run the following query. \n",
```suggestion
    "To use the <strong>elec_predict_model</strong> created in the previous step for prediction of <strong>building_elec_test</strong>, run the following query.\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "<p>The dataset provided by ThanoSQL is already refined for predicting. However, if you want to use your own time series dataset to predict using a time series model, you must merge some last par
```suggestion
    "<p>The dataset provided by ThanoSQL is already refined for prediction. However, if you want to use your own time series dataset to predict using a time series model, you must merge the train dataset with the configured encoder length as an answer to the test dataset. e.g. If you set the model encoder length to 860 and the test dataset's "time_idx" starts at 1000, the "time_idx" of 140–999 data points should be merged into the test dataset.</p>\n",
```

2023-01-04 02:35 UTC, inwookie commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "        result_col=\"tft_result\"\n",
```suggestion
    "        result_col=\'tft_result\'\n",
```

2023-01-04 04:42 UTC, Indoo-Park commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "- You can predict next month's sales of your business in advance. This will help you to set up better strategies for your business based on the future production volume or else.\n",
수정완료

2023-01-04 04:43 UTC, Indoo-Park commented on tutorial_en/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "- You can predict next month's sales of your business in advance. This will help you to set up better strategies for your business based on the future production volume or else.\n",
> 
수정완료

2023-01-04 07:56 UTC, yeemh commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "이전 단계에서 생성한 시계열 예측 모델을 사용해 테스트 세트의 1주일 전력 사용량을 예측해 봅니다. 테스트용 데이터 세트(학습에 이용되지 않은 데이터 테이블, <strong>building_elec_test</strong>)를 사용합니다."
@Indoo-Park 여기서부터 누락됐어요

2023-01-04 08:02 UTC, Indoo-Park commented on tutorial/thanosql_ml/timeseries/timeseries_forecasting.ipynb
> +    "## __4. 생성된 모델 평가__\n",
예측 후  예측된 결과를 평가하는 튜토리얼이라 이 커멘트는 기각하겠습니다

2023-01-04 08:33 UTC, yeemh approved these changes
HERE WE GO

2023-01-04 08:42 UTC, merged